sID = {...
    ... amblyopia:
    'AM_LE_G_JQ_48',...
    ...'AM_LE_G_KK_28',... kerataconus
    'AM_LE_G_YK_67',... 
    'AM_LE_L_CJ_38',...
    'AM_LE_L_HQ_72',...
    'AM_LE_L_IE_68',...
    'AM_LE_L_IQ_63',...
    'AM_LE_L_WA_43',...
    'AM_RE_G_RF_20',...
    'AM_RE_L_BH_69',...
    'AM_RE_L_FZ_43',...
    'AM_RE_L_IA_22',...
    'AM_RE_L_KR_58',...
    'AM_RE_L_RK_15',...
    'AM_RE_L_YP_39',... 
    ... non-amblyopic binocular disorder:
    'BD_G_AU_47',...
    'BD_G_BK_33',...
    'BD_LE_G_ES_62',...
    'BD_LE_L_EI_19',... previously: 'AM_LE_L_EI_19'
    'BD_LE_L_KC_19',... previously: 'AM_LE_KC_19'
    'BD_LE_L_YH_47',...
    'BD_LE_L_YV_15',... previously: 'AM_LE_L_YV_15'
    'BD_RE_L_WI_56',... 
    ... normally-sighted controls:
    'NS_G_AU_22',...
    'NS_G_BZ_66',...
    'NS_G_HK_50',... 
    'NS_G_QP_15',...
    'NS_G_RA_57',...
    'NS_G_RE_17',...
    'NS_L_AA_53',...         
    'NS_L_IR',...            
    'NS_L_KA_18',...         
    'NS_L_KH_27',...
    'NS_L_PZ_47',...
    'NS_L_VD_28',...   
    'NS_L_XQ_17',...
    'NS_L_YA',...            
    'NS_L_YI_34',...         
    'NS_L_YL_16'};